---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30001
      protocol: TCP
  selector:
    name: web
...
